spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/java-practice/springjpa
    username: sa
    password:
    driver-classname: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibername:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
