server:
  hostname: 0.0.0.0
  port: 5656

security.auth.enabled: false

transactionsRateDisplayLimit: 50

kafka:
  topic:
    transactions: livetransactions
    rules: rules
    alerts: alerts
    latency: latency
    current-rules: current-rules
    filters: filters
  listeners:
    transactions.id: transactions-listener

  bootstrap-servers: localhost:9092 #211.253.8.155:9092

druid:
  server: http://localhost:8888 #211.253.8.155:8888

web-socket:
  topic:
    transactions: /topic/transactions
    alerts: /topic/alerts
    latency: /topic/latency

management.endpoints.web.exposure.include: mappings, loggers
spring:
  jpa:
#    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
      url: jdbc:mysql://localhost:3306/iot?serverTimezone=UTC #211.253.8.155:50008/iot
      username: root
      password: qnsekd1!


  # h2.console.enabled: true
  thymeleaf.cache: false
#  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #211.253.8.155:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer